
name: Test run deployment

on: 
  push:
  pull_request:
   branches: [ "pavandev", "pavannp" ]  
  workflow_dispatch:
  


jobs:
   Build:
    runs-on: ubuntu-latest

    steps:
      - name: printing statement
        run: echo This is Build



   DevDeployment:
    if: github.event.ref == 'refs/heads/pavandev'
    
    needs: Build
    environment:
     name: Development
    runs-on: ubuntu-latest

    steps:
     - name: Print statement
       run: echo "Development deployment"



   SandboxDeployment:
    name: Sandbox environment
    if: github.event.ref == 'refs/heads/pavannp'
    needs: Build
    environment:
     name: Sandbox

   
    runs-on: ubuntu-latest
    steps:
     - name: Print statement
       run: echo "This is sandbox"

   ProductionDeployment:
   
    runs-on: ubuntu-latest
    needs: SandboxDeployment
    environment:
     name: Production
    steps:
     
     - name: Print statement
       run: echo "This is Production"
      








    
       
